version: 1

build_arg_defaults: 
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: "-c"
  EE_BASE_IMAGE: registry.redhat.io/ansible-automation-platform-22/ee-minimal-rhel8:latest
ansible_config: 'ansible.cfg' 

dependencies: 
  galaxy: requirements.yml
  python: requirements.txt
  system: system-reqs.txt

additional_build_steps:
  prepend: |
    RUN pip3 install --upgrade pip setuptools

  append: |
    RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
        unzip awscliv2.zip && \
        ./aws/install && \
        ls -la /etc

