apiVersion: shipwright.io/v1alpha1
kind: Build
metadata:
  name: ansible-builder-automated-sm-ee
spec:
  source:
    url: https://github.com/bdumont01/ansible-builder-shipwright
    contextDir: automated-sm-build
    revision: main
  output:
    image: image-registry.openshift-image-registry.svc:5000/ansible-builder-shipwright/automated-sm-ee:latest
  strategy:
    name: ansible-builder
    kind: ClusterBuildStrategy
