apiVersion: shipwright.io/v1alpha1
kind: Build
metadata:
  name: ansible-builder-lab-ee
spec:
  source:
    url: https://github.com/bdumont01/ansible-builder-shipwright/lab-ee-build
    contextDir: build-files
    revision: main
  output:
    image: image-registry.openshift-image-registry.svc:5000/ansible-builder-shipwright/lab-ee:latest
  strategy:
    name: ansible-builder
    kind: ClusterBuildStrategy
